### ISSUE TITLE
Strange boxes around the letters

### ISSUE THREAD

**Issue by geekkid1** [Clarvel/TennoTyper#4]
I had found this tool a while ago and really liked it. But I got on today to try to demonstrate it for one of my friends and these bounding boxes appeared around all the glyphs. Made it look really bad.

Here's how it appeared in the preview:
![image](https://user-images.githubusercontent.com/23391383/78152730-353d6d80-7408-11ea-8d92-d151f3d6458e.png)

And pretty much the same in the save:
![image](https://user-images.githubusercontent.com/23391383/78152780-4ab29780-7408-11ea-9084-51c8b58ae7dd.png)

**Comment by Clarvel** [comment]
that's a debug mode i added for testing purposes. press the 'alt' key to
toggle it on/off

**Comment by geekkid1** [comment]
Thank you, I will do that!
